const STOP = 'Sharp or pinching pain is a stop. Muscular burn is not. Numbness or tingling is a stop.';

function guide(id, title, dose, pose, form, avoid, feel, mods) {
  return {
    id,
    title,
    dose,
    pose,
    strips: [pose],
    form: [dose, ...form],
    avoid,
    feel,
    notFeel: [STOP, 'Stop the set if any of those show up. Do not push through.'],
    mods,
  };
}

export const PATH_GUIDES = [
  guide(
    'explosive-push-ups',
    'Explosive push-ups',
    '12 explosive push-ups',
    'push-up',
    [
      'Hands under the shoulders. Body one line from head to heels.',
      'Lower under control until the chest is a fist off the floor.',
      'Press hard enough that the hands can leave the floor, then land with soft elbows.',
    ],
    ['Hips sagging to buy height', 'Elbows flared straight out', 'Landing on locked elbows'],
    ['Chest and the back of the arms', 'A quiet landing'],
    ['Regular push-ups.', 'Leave the hands on the floor and press fast instead of leaving the ground.'],
  ),
  guide(
    'broad-jump-burpees',
    'Broad-jump burpees',
    '10 broad-jump burpees',
    'burpee',
    [
      'Drop to a straight plank, then jump the feet back in.',
      'From the stand, jump forward and land with both feet, knees soft.',
      'Turn around or step back to the line and go again.',
    ],
    ['Hips sagging in the plank', 'Locked knees on the landing', 'Knees caving inward'],
    ['Chest, shoulders, and legs sharing the jump', 'A landing you can hold'],
    ['Step the feet back.', 'A short hop instead of a long jump.'],
  ),
  guide(
    'tuck-jumps',
    'Tuck jumps',
    '15 tuck jumps',
    'tuck-jump',
    [
      'Stand tall. Dip, then leave the floor.',
      'Knees come up. Land on the whole foot with soft knees.',
      'Stand again before the next jump.',
    ],
    ['Knees caving on the landing', 'Stiff-leg landings', 'Pitching forward'],
    ['Quads and calves', 'A landing quiet enough to continue'],
    ['Jump squats with a small hop.', 'Squats with no jump.'],
  ),
  guide(
    'jumping-lunges',
    'Jumping lunges',
    '16 jumping lunges, 8 each leg',
    'jumping-lunge',
    [
      'Split stance. Both knees bend, back knee toward the floor.',
      'Switch the legs in the air and land in the other lunge.',
      'The front knee stays over the foot.',
    ],
    ['Front knee caving inward', 'Landing on a locked front knee', 'A short stance that dumps the weight forward'],
    ['Quads and glutes', 'A stable front foot'],
    ['Reverse lunges with no jump.', 'Split squats, one leg at a time.'],
  ),
  guide(
    'side-plank',
    'Side plank',
    '30 seconds, 15 each side',
    'side-plank',
    [
      'Forearm under the shoulder. Feet stacked or staggered.',
      'Hips lift so the body is one line from ear to ankle.',
      'Switch sides when the first hold is done.',
    ],
    ['Hips dropping', 'Shoulder shrugging toward the ear', 'Holding the breath'],
    ['The side of the waist and the shoulder', 'A line you can keep'],
    ['Bottom knee down, body straight from head to knee.', 'A shorter hold.'],
  ),
  guide(
    'high-knees',
    'Controlled high knees',
    '40 reps, 20 each leg',
    'high-knees',
    [
      'Stand tall. Drive one knee to hip height, then the other.',
      'The pace stays even. The chest stays up.',
      'Land on the ball of the foot, not a locked heel.',
    ],
    ['Leaning back', 'Knees barely lifting', 'Slamming the feet'],
    ['Hip flexors and calves', 'Breath that matches the steps'],
    ['March in place with the same knee height.'],
  ),
  guide(
    'russian-twists',
    'Russian twists',
    '20 reps, 10 each side',
    'russian-twist',
    [
      'Sit, knees bent, heels light or down. Lean back until the abs hold you.',
      'Rotate the ribs. The head follows the chest.',
      'Each side is one rep.',
    ],
    ['Yanking the neck', 'Rounding and collapsing the lower back', 'Using the arms to throw the turn'],
    ['Obliques', 'A turn that comes from the ribs'],
    ['Feet on the floor.', 'A smaller turn you can keep slow.'],
  ),
  guide(
    'plyo-squats',
    'Plyo squats',
    '15 plyo squats',
    'jump-squat',
    [
      'Squat until the thighs are at least parallel.',
      'Drive up and leave the floor a little.',
      'Land and sit straight into the next squat.',
    ],
    ['Knees caving inward', 'Heels coming up the whole squat', 'Landing on locked knees'],
    ['Quads and glutes', 'A soft landing'],
    ['Squats with no jump.', 'A smaller hop.'],
  ),
  guide(
    'slow-push-ups',
    'Slow push-ups',
    '10 slow push-ups, 4-second descent',
    'push-up',
    [
      'Hands under the shoulders. Body one line.',
      'Take four seconds to lower until the chest is a fist off the floor.',
      'Press back up without sagging.',
    ],
    ['Dropping the chest in one count', 'Hips sagging', 'Elbows flared straight out'],
    ['Chest and the back of the arms', 'The same line at the bottom as at the top'],
    ['The same four-second descent on the knees.', 'Hands on a bench.'],
  ),
  guide(
    'wall-sit',
    'Wall sit',
    '45-second wall sit',
    'wall-sit',
    [
      'Back flat on a wall. Feet a step forward.',
      'Slide until the knees are near a right angle. Knees stay over the ankles.',
      'Hold. The heels stay down.',
    ],
    ['Knees caving inward', 'Heels lifting', 'The lower back leaving the wall'],
    ['Quads', 'A burn you can still breathe through'],
    ['A higher seat.', 'A shorter hold.'],
  ),
  guide(
    'dead-bug',
    'Dead bug',
    '16 reps, 8 each side',
    'dead-bug',
    [
      'Lie on the back. Arms up. Hips and knees at right angles.',
      'Press the lower back into the floor.',
      'Reach the opposite arm and leg away, then return. Switch sides.',
    ],
    ['The lower back arching off the floor', 'Holding the breath', 'Dropping the free leg too low to keep the back down'],
    ['The deep abs holding the back down', 'A slow reach'],
    ['Keep the knees bent and move only the arms.', 'A smaller reach.'],
  ),
  guide(
    'side-plank-hold',
    'Side plank hold',
    '30 seconds, 15 each side',
    'side-plank',
    [
      'Forearm under the shoulder. Hips up.',
      'Hold the line. Do not twist the chest toward the floor.',
      'Switch sides.',
    ],
    ['Hips dropping', 'Holding the breath', 'The shoulder collapsing'],
    ['The side of the waist', 'A quiet lower back'],
    ['Bottom knee down.', 'A shorter hold.'],
  ),
  guide(
    'slow-squats',
    'Slow squats',
    '12 slow squats, 4-second descent',
    'squat',
    [
      'Feet about shoulder width. Heels stay down.',
      'Take four seconds to sit until the thighs are at least parallel.',
      'Stand without bouncing at the bottom.',
    ],
    ['Knees caving inward', 'Heels lifting', 'The lower back rounding at the bottom'],
    ['Quads and glutes', 'The same depth on the last rep'],
    ['A higher squat you can lower slowly.', 'Hold a door frame for balance.'],
  ),
  guide(
    'superman-hold',
    'Superman hold',
    '30-second superman hold',
    'superman',
    [
      'Lie face down. Arms forward.',
      'Lift the chest and the legs a little. The neck stays long.',
      'Hold. The ribs do not have to clear the floor by a foot.',
    ],
    ['Yanking the head up', 'Holding the breath', 'A sharp pinch in the lower back'],
    ['The back of the shoulders and the glutes', 'A small, even lift'],
    ['Lift only the chest.', 'A shorter hold.'],
  ),
  guide(
    'glute-bridge-hold',
    'Glute bridge hold',
    '40-second glute bridge hold',
    'glute-bridge',
    [
      'Lie on the back. Knees bent. Heels down.',
      'Press the hips up until the body is a line from knee to shoulder.',
      'Hold. Ribs stay down.',
    ],
    ['Overarching the lower back', 'The knees falling apart', 'Holding the breath'],
    ['Glutes', 'A line you can keep without the back taking it'],
    ['A lower bridge.', 'A shorter hold.'],
  ),
  guide(
    'mountain-controlled',
    'Controlled mountain climbers',
    '20 reps, 10 each leg',
    'mountain',
    [
      'Hands under the shoulders. Body one line.',
      'Bring one knee in slowly. Set the foot back. Then the other leg.',
      'The hips stay level. No bounce.',
    ],
    ['Hips piking up', 'Hips sagging', 'Bouncing off the toes'],
    ['The abs holding the plank', 'Hip flexors doing the step'],
    ['Hands on a bench.', 'A slower step with the knees down between reps.'],
  ),
  guide(
    'knee-push-ups',
    'Knee push-ups',
    '12 knee push-ups',
    'knee-push-up',
    [
      'Knees down. Body one line from head to knees. Hips do not fold.',
      'Lower until the chest is a fist off the floor.',
      'Press back up without shrugging.',
    ],
    ['Hips folded so the move becomes a dip', 'Elbows flared straight out', 'Half reps'],
    ['Chest and the back of the arms', 'The same line on every rep'],
    ['Hands on a bench, knees down.', 'A smaller range you can finish straight.'],
  ),
  guide(
    'squat-still',
    'Squats',
    '15 squats, no jump',
    'squat',
    [
      'Feet about shoulder width.',
      'Sit until the thighs are at least parallel. Heels stay down.',
      'Stand. The feet never leave the floor.',
    ],
    ['Knees caving inward', 'Heels lifting', 'The lower back rounding'],
    ['Quads and glutes', 'A stand you can pause'],
    ['A higher squat.', 'Hold a door frame for balance.'],
  ),
  guide(
    'standing-marches',
    'Standing marches',
    '30 marches, 15 each leg',
    'march',
    [
      'Stand tall.',
      'Lift one knee to hip height, set it down, then the other.',
      'The chest stays up. The pace stays even.',
    ],
    ['Leaning back', 'Holding the breath', 'Locking the standing knee hard'],
    ['Hip flexors', 'A quiet step'],
    ['A lower knee lift.', 'One hand on a wall.'],
  ),
  guide(
    'knee-plank',
    'Knee plank',
    '30-second knee plank',
    'knee-plank',
    [
      'Knees down. Forearms or hands under the shoulders.',
      'One line from head to knees. Hips neither sag nor pike.',
      'Breathe and hold.',
    ],
    ['Hips folded', 'Hips sagging', 'Holding the breath'],
    ['The midsection and shoulders', 'A line you can keep'],
    ['A shorter hold.', 'Hands on a bench.'],
  ),
  guide(
    'side-bends',
    'Standing side bends',
    '20 reps, 10 each side',
    'side-bend',
    [
      'Stand tall. One hand slides down the leg.',
      'The hips stay facing forward. The move is a side bend, not a twist.',
      'Come back up and switch sides.',
    ],
    ['Leaning forward', 'Locking the knees and bouncing', 'Yanking the neck'],
    ['The side of the waist', 'A range you can reverse slowly'],
    ['A smaller bend.', 'One hand on a wall.'],
  ),
  guide(
    'glute-bridges',
    'Glute bridges',
    '15 glute bridges',
    'glute-bridge',
    [
      'Lie on the back. Knees bent. Heels down.',
      'Press the hips up until the body is a line from knee to shoulder.',
      'Lower with control.',
    ],
    ['Overarching the lower back', 'The knees falling outward', 'Pushing through the neck'],
    ['Glutes', 'A pause at the top'],
    ['A smaller lift.', 'Feet closer to the hips if the hamstrings cramp.'],
  ),
  guide(
    'step-back-lunges',
    'Step-back lunges',
    '16 reps, 8 each leg',
    'lunge',
    [
      'Stand tall. Step one foot back.',
      'Bend both knees. The front knee stays over the foot.',
      'Push through the front foot and stand. Switch legs.',
    ],
    ['Front knee caving inward', 'Slamming the back knee', 'A short step that dumps the weight forward'],
    ['Quads and glutes', 'A front foot that stays flat'],
    ['A shorter step.', 'One hand on a wall.'],
  ),
  guide(
    'leg-raises',
    'Lying leg raises',
    '12 lying leg raises',
    'leg-raise',
    [
      'Lie on the back. Press the lower back into the floor.',
      'Lift straight legs until the hips start to help, then lower.',
      'Stop the lower if the back peels off the floor. Bend the knees instead.',
    ],
    ['The lower back arching off the floor', 'Holding the breath', 'Using a swing of the legs'],
    ['The lower abs holding the back down', 'A controlled lower'],
    ['Bend the knees.', 'One leg at a time.'],
  ),
];
